#!/bin/sh -e
#
# Prepare Mailman at build time
#

die()
{
    echo "$@" 1>&2
    exit 1
}

# TODO: This list should come from a common source.  Docker-entrypoint
# uses it, too.

for DIR in \
    /etc/mailman \
    /var/lib/mailman \
    /var/log/httpd \
    /var/log/mailman \
    /var/run/mailman \
    /var/spool/mailman
do
    DIST="${DIR}-dist"
    if [ ! -e "${DIST}" ]
    then
	mv "${DIR}" "${DIR}-dist"
    else
	echo "${DIR} has already been renamed."
    fi
done


# Let the web server do mailman things
usermod -G mailman apache

# Unlock the mailman account so it can be su'd to.
usermod \
    --password '*' \
    --shell '/bin/bash' \
    mailman
